#!/bin/sh

reload(){ trap - USR1; pkill -P $$; exec $0; }
trap reload USR1

polybar_config="$(dirname $0)/../config.ini"

for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar -c "$polybar_config" &
done

wait
