[module/wlan]
type = internal/network
interface = wlan0
interval = 3.0

format-connected = <ramp-signal> <label-connected>
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
;ramp-signal-0 = 
;ramp-signal-1 = 
;ramp-signal-2 = 
;ramp-signal-3 = 
;ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = enp9s0
interval = 3.0

format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}
