#!/bin/bash

PA_JACK_SINK="jack_out"

if ! jack_control status; then
    # Start JACK
    jack_control start
    jack_control ds alsa
    #jack_control dps device hw:USB
    jack_control dps rate 44100
    jack_control dps nperiods 2
    jack_control dps period 256
    # Setup PulseAudio bridge
    pacmd set-default-sink jack_out
    while read line; do
        input=$(echo $line | cut -f2 -d' ')
        echo "Moving input: $input to $PA_JACK_SINK"
        pacmd move-sink-input $input $PA_JACK_SINK
    done < <(pacmd list-sink-inputs | grep index);
    # User notification
    notify-send -i info -t 2000 "Audio mode enabled"
    # Alsa midi bridge
    if [[ $(pgrep -cx a2jmidid) -eq 0 ]]; then
        nohup a2jmidid -e >/dev/null 2>&1 &
        notify-send -i info -t 2000 "Midi bridge started"
    fi
else
    # Stop JACK
    jack_control stop
    # Kill Alsa midi bridge
    if [[ $(pgrep -cx a2jmidid) -ge 1 ]]; then
        killall -e -9 a2jmidid
        notify-send -i info -t 2000 "Midi bridge stopped"
    fi
    # User notification
    notify-send -i info -t 2000 "Audio mode disabled"
fi
