#!/bin/bash
set -e

#----------------------------------------------------------------------
# Help
#----------------------------------------------------------------------
USAGE="Usage: $(basename $0) <command> [args]"
HELP="\
$(basename $0) <command> [args]

Commands:
  scale [value]          Show or set scale value
  dpi   [value]          Show or set dpi value
  autodetect             Try to autodetect scale value

Options:
  -h, --help             Print current help message
"

die() { echo >&2 "$*"; exit 1; }
usage() { die "$USAGE"; }
help() { echo "$HELP"; }

#----------------------------------------------------------------------
# Constants
#----------------------------------------------------------------------
DPICTL_CONF_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/dpictl
ENVD_HIDPI_CONF=${XDG_CONFIG_HOME:-$HOME/.config}/environment.d/hidpi.conf
XORG_MONITOR_CONF=/etc/X11/xorg.conf.d/*-monitor.conf

#----------------------------------------------------------------------
# Templates
#----------------------------------------------------------------------
read -r -d '' ENVD_HIDPI_FILE << EOM || :
# HiDPI settings for GTK3+
GDK_SCALE={gtk_scale}
GDK_DPI_SCALE={gtk_dpi_scale}

# HiDPI settings for QT
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_ENABLE_HIGHDPI_SCALING=1
PLASMA_USE_QT_SCALING=1
EOM

#----------------------------------------------------------------------
# Helpers
#----------------------------------------------------------------------
valuefile() {
    local valuename="$1"
    local valuefile=$DPICTL_CONF_DIR/$valuename
    echo $valuefile
}

scale2dpi() {
    local scale="$1"
    local dpi=$(bc -l <<< "scale=2; 96.0 * $scale / 100.0")
    printf "%.0f\n" $dpi
}

dpi2scale() {
    local dpi="$1"
    local scale=$(bc -l <<< "scale=2; ($dpi / 96.0) * 100.0")
    printf "%.0f\n" $scale
}

resolution() {
    xrandr | awk '/primary/{sub(/+.*$/,"",$4); sub(/x/," ",$4); print $4}'
}

display_size() {
    local size
    if [ -f $XORG_MONITOR_CONF ]; then
        size=($(awk '/\s+DisplaySize/{print $2, $3}' $XORG_MONITOR_CONF))
    fi
    if [ ${#size[@]} -eq 0 ]; then
        size=($(xrandr | awk '/primary/{sub(/\(.*\)/,"",$0); sub(/mm/,"",$5); sub(/mm/,"",$7); print $5, $7}'))
    fi
    echo "${size[@]}"
}

autodetect_dpi() {
    local res=($(resolution))
    local size=($(display_size))

    local rw=${res[0]}
    local rh=${res[1]}
    local sw=${size[0]}
    local sh=${size[1]}

    local dpi=$(bc -l <<< "scale=2; sqrt($rw ^ 2 + $rh^2) / (sqrt($sw ^ 2 + $sh ^ 2) / 25.4)")
    printf "%.0f\n" $dpi
}

gtk_scale() {
    local scale="$1"

    local gtk_scale="1"
    local gtk_dpi_scale="1.0"

    if [ $scale -ge 250 ]; then
        gtk_scale="3"
        gtk_dpi_scale="0.34"
    elif [ $scale -ge 125 ]; then
        gtk_scale="2"
        gtk_dpi_scale="0.5"
    else
        gtk_scale="1"
        gtk_dpi_scale="1.0"
    fi

    echo $gtk_scale $gtk_dpi_scale
}

update_env_file () {
    local scale="$1"
    local gtk_scales=($(gtk_scale "$scale"))
    mkdir -p $(dirname "$ENVD_HIDPI_CONF")
    echo "$ENVD_HIDPI_FILE" | sed \
        -e "s/{gtk_scale}/${gtk_scales[0]}/g" \
        -e "s/{gtk_dpi_scale}/${gtk_scales[1]}/g" \
      > "$ENVD_HIDPI_CONF"
}

update_scale() {
    local scale="$1"
    update_env_file $scale
    echo $scale > "$scalefile"
}

#----------------------------------------------------------------------
# Commands
#----------------------------------------------------------------------
scale() {
    local scale="$1"

    local scalefile=$(valuefile "scale")
    mkdir -p $(dirname "$scalefile")

    if [ -z $scale ]; then
        if [ ! -f "$scalefile" ]; then
            update_scale "$(autodetect)"
        fi
        scale=$(cat "$scalefile")
        echo $scale
    else
        update_scale "$scale"
    fi
}

dpi() {
    local dpi="$1"

    local scalefile=$(valuefile "scale")
    mkdir -p $(dirname "$scalefile")

    if [ -z $dpi ]; then
        if [ ! -f "$scalefile" ]; then
            update_scale "$(autodetect)"
        fi
        local scale=$(cat "$scalefile")
        local dpi=$(scale2dpi "$scale")
        echo $dpi
    else
        local scale=$(dpi2scale "$dpi")
        update_scale "$scale"
    fi
}

autodetect() {
    local dpi=$(autodetect_dpi)
    dpi2scale "$dpi"
}

#----------------------------------------------------------------------
# Entrypoint
#----------------------------------------------------------------------
case "$#" in
    0)
        usage ;;
    *)
        for arg in "$@"; do
            case "$arg" in
                -h|--help)
                    help
                    exit 0
                    ;;
                -*)
                    echo "Unexpected option $arg" >&2
                    die "See '$(basename $0) --help' for more information"
                    ;;
            esac
        done
esac

cmd="$1"
shift

case "$cmd" in
    scale)
        [ $# -gt 1 ] && die "Usage: $(basename $0) scale [value]"
        scale "$1"
        ;;
    dpi)
        [ $# -gt 1 ] && die "Usage: $(basename $0) dpi [value]"
        dpi "$1"
        ;;
    autodetect)
        [ $# -ne 0 ] && die "Usage: $(basename $0) autodetect"
        autodetect
        ;;
    *)
        echo "Unexpected command $cmd" >&2
        die "See '$(basename $0) --help' for more information"
esac
