#!/bin/bash

# Print to stderr and exit with non-success error code
die() { echo "$*" 1>&2; exit 1; }

# If used with version flag skip sandboxing
if (( $# == 2 )) && [[ "$1" = "wine" && "$2" = "--version" ]]; then
    wine --version
    exit 0
fi

# No WINEPREFIX specified
if [ -z "$WINEPREFIX" ]; then
    # Try detect it
    echo Warning: \$WINEPREFIX was not specified, trying to autodetect it >&2
    path=$(pwd)
    while [[ "$path" != "" && ! -e "$path/.wine" ]]; do
        path=${path%/*}
    done
    # Exit if detection failed
    if [ -z "$path" ]; then
        echo Error: \$WINEPREFIX could not be detected >&2
        exit 1
    fi
    export WINEPREFIX=$path/.wine
fi
echo Using \$WINEPREFIX in $WINEPREFIX

# Sandbox location
SANDBOX="$WINEPREFIX/../"
[ ! -d "$SANDBOX" ] && die "Invalid sandbox location" || echo Using sandbox in $SANDBOX >&2

# Jail it
yabridge_flags=()
if compgen -G $XDG_RUNTIME_DIR/yabridge-*/ > /dev/null; then
    for d in $XDG_RUNTIME_DIR/yabridge-*/; do
        yabridge_flags+=("--bind" "$d" "$d");
    done
fi

bwrap \
    --die-with-parent \
    --new-session \
    --unshare-user \
    --unshare-ipc \
    --unshare-uts \
    --unshare-cgroup \
    --share-net \
    --clearenv \
    --proc /proc \
    --tmpfs /tmp \
    --dev /dev \
    --dev-bind /dev/dri /dev/dri \
    --dev-bind /dev/shm /dev/shm \
    --dev-bind /dev/snd /dev/snd \
    --dev-bind /dev/input /dev/input \
    --symlink usr/bin /bin \
    --symlink usr/lib /lib \
    --symlink usr/lib64 /lib64 \
    --ro-bind /usr/bin /usr/bin \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib32 /usr/lib32 \
    --ro-bind /usr/lib64 /usr/lib64 \
    --ro-bind /usr/share /usr/share \
    --ro-bind /etc/fonts /etc/fonts \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --ro-bind /sys/dev/char /sys/dev/char \
    --ro-bind /sys/devices/pci0000:00 /sys/devices/pci0000:00 \
    --ro-bind /sys/class/input /sys/class/input \
    --ro-bind /sys/class/hidraw /sys/class/hidraw \
    --ro-bind /sys/devices/system/cpu /sys/devices/system/cpu \
    --ro-bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X0 \
    --ro-bind $XDG_RUNTIME_DIR/pipewire-0 $XDG_RUNTIME_DIR/pipewire-0 \
    --ro-bind $XDG_RUNTIME_DIR/pulse $XDG_RUNTIME_DIR/pulse \
    --bind $SANDBOX $SANDBOX \
    --bind $SANDBOX $HOME \
    --bind $HOME/.Xauthority $HOME/.Xauthority \
    --setenv PATH /usr/local/sbin:/usr/local/bin:/usr/bin \
    --setenv LANG $LANG \
    --setenv HOME $HOME \
    --setenv DISPLAY $DISPLAY \
    --setenv XDG_RUNTIME_DIR "/run/user/$UID" \
    --setenv WINEDLLOVERRIDES "libglesv2.dll=d" \
    --setenv YABRIDGE_NO_WATCHDOG 1 \
    "${yabridge_flags[@]}" \
    "$@"
