#!/bin/bash
set -e

# Set background color to match mutt theme
ansictl set background '#2E3440'

# Pick mail
lastmail=$HOME/.cache/.lastmail
if [ "$1" = "-p" ] || [ ! -f "$lastmail" ]; then
    mail=$(mailconf ls | fzf)
    [ ! -z $mail ] && echo $mail > "$lastmail"
fi
mail=$(cat $lastmail)
[ -z $mail ] && exit 1

# Launch mutt along with its companions, exposing the encrypted mail directory
echo Opening mail $mail
encdir expose $HOME/.cache/mail -- /bin/bash << EOF
{
    keyctl new_session >/dev/null

    mailconf daemon $mail |& systemd-cat -t mailr &
    TERM=xterm-direct MAIL=$mail neomutt

    mailconf control $mail exit
    wait
} </dev/tty
EOF

# Reset background color
ansictl reset background
