#!/bin/bash
set -e

# Setup cleanup trap
cleanup() {
    # Remove SIGTERM trap
    trap - SIGTERM

    # Reset background color
    ansictl reset background

    # Sends a SIGTERM to the whole process group, killing also descendants
    [ ! -z "$(jobs -p)" ] && kill -- -$$
}
trap cleanup SIGINT SIGTERM EXIT

# Set background color to match mutt theme
ansictl set background '#2E3440'

# Launch mutt along with its companions, exposing the encrypted mail directory
mail=$(mailconf ls | fzf)
encdir expose $HOME/.cache/mail -- /bin/bash << EOF
{
    exec < /dev/tty
    (
        mailconf sync  $mail &>/dev/null
        mailconf index $mail &>/dev/null
        mailconf watch $mail &>/dev/null
    ) &
    TERM=xterm-direct MAIL=$mail neomutt
    exit
}
EOF
