#!/bin/bash
set -e

# Setup cleanup trap
cleanup() {
    # Remove SIGTERM trap
    trap - SIGTERM

    # Reset background color
    ansictl reset background

    # Sends a SIGTERM to the whole process group, killing also descendants
    [ ! -z "$(jobs -p)" ] && kill -- -$$
}
trap cleanup SIGINT SIGTERM EXIT

# Set background color to match mutt theme
ansictl set background '#2E3440'

# Pick mail
lastmail=$HOME/.cache/.lastmail
if [ "$1" = "-p" ] || [ ! -f "$lastmail" ]; then
    mail=$(mailconf ls | fzf)
    [ ! -z $mail ] && echo $mail > "$lastmail"
fi
mail=$(cat $lastmail)
[ -z $mail ] && exit 1

# Launch mutt along with its companions, exposing the encrypted mail directory
echo Opening mail $mail
encdir expose $HOME/.cache/mail -- /bin/bash << EOF
{
    exec < /dev/tty
    (
        mailconf sync  $mail &>/dev/null
        mailconf index $mail &>/dev/null
        mailconf watch $mail &>/dev/null
    ) &
    TERM=xterm-direct MAIL=$mail neomutt
    exit
}
EOF
