#!/bin/bash
set -e

#----------------------------------------------------------------------
# Help
#----------------------------------------------------------------------
USAGE="Usage: $(basename $0) <command> [<args>]"
HELP="\
$(basename $0) <command> [<args>]

Commands:
  add     <email>   Add new mail configuration
  sync    <email>   Sync maildir folder
  watch   <email>   Watch for new mails
  daemon  <email>   Run daemon that listens for control commands
  control <email>   Send control command to a running daemon
  rm      <email>   Remove existing mail configuration
  ls                List all mail configurations

Options:
  -h, --help      Print current help message
"

die() { echo >&2 "$*"; exit 1; }
usage() { die "$USAGE"; }
help() { echo "$HELP"; }
log() { echo -e "\033[1m> $@\033[0m" >&2; }
prefix() { while read -r line; do echo "$1$line"; done }

#----------------------------------------------------------------------
# Constants
#----------------------------------------------------------------------
MAIL_CONF_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/mailconf
MAIL_CACHE_DIR=${XDG_CACHE_HOME:-$HOME/.cache}/mail
MAIL_STATE_DIR=${XDG_STATE_HOME:-$HOME/.local/state}/mail

#----------------------------------------------------------------------
# Helpers
#----------------------------------------------------------------------
mailconfdir() {
    local mail="$1"
    local mailconfdir=$MAIL_CONF_DIR/$mail
    echo $mailconfdir
}

mailcachedir() {
    local mail="$1"
    local mailcachedir=$MAIL_CACHE_DIR/$mail
    echo $mailcachedir
}

mailstatedir() {
    local mail="$1"
    local mailstatedir=$MAIL_STATE_DIR/$mail
    echo $mailstatedir
}

reltohome() {
    echo $1 | sed "s|$HOME|~|"
}

populate() {
    local template=$1
    echo "$template" | sed \
        -e "s/{host}/$2/" \
        -e "s/{mail}/$3/"
}

#----------------------------------------------------------------------
# Templates
#----------------------------------------------------------------------
read -r -d '' MBSYNCRC << EOM || :
Create Both
Expunge Both
SyncState *
CopyArrivalDate yes

IMAPAccount mail-account
Host {host}
Port 993
User {mail}
AuthMechs XOAUTH2
PassCmd "$MAIL_CONF_DIR/{mail}/passfetch"
TLSType IMAPS
TLSVersions +1.3
CertificateFile /etc/ssl/certs/ca-certificates.crt

IMAPStore mail-remote
Account mail-account

MaildirStore mail-local
Path $(reltohome $MAIL_CACHE_DIR)/{mail}/data/
Inbox $(reltohome $MAIL_CACHE_DIR)/{mail}/data/Inbox
SubFolders Verbatim

Channel mail
Far :mail-remote:
Near :mail-local:
Patterns *
EOM

read -r -d '' IMAPNOTIFYRC << EOM || :
configurations:
  - host: "{host}"
    port: 993
    tls: true
    tlsOptions:
      rejectUnauthorized: true
      starttls: false
    username: "{mail}"
    passwordCMD: "$MAIL_CONF_DIR/{mail}/passfetch"
    xoAuth2: true
    boxes:
      - mailbox: "Inbox"
        onNewMail: "mailconf control {mail} sync"
        onNewMailPost: SKIP
EOM

read -r -d '' MSMTPRC << EOM || :
defaults
auth           on
tls            on
tls_starttls   off
tls_trust_file /etc/ssl/certs/ca-certificates.crt
auth           oauthbearer

account        mail
host           {host}
port           465
from           {mail}
user           {mail}
passwordeval   "$MAIL_CONF_DIR/{mail}/passfetch"
EOM

read -r -d '' NOTMUCHRC << EOM || :
[database]
path=$(reltohome $MAIL_CACHE_DIR)/{mail}/data/

[user]
name={mail}
primary_email={mail}

[new]
ignore=.uidvalidity;.mbsyncstate;.mbsyncstate.lock

[search]
exclude_tags=deleted;spam

[maildir]
synchronize_flags=true
EOM

read -r -d '' MUTTRC << EOM || :
set my_mail = "{mail}"
set my_conf = "$(reltohome $MAIL_CONF_DIR)/{mail}"
set header_cache = "$(reltohome $MAIL_CACHE_DIR)/{mail}/mutt/"
set message_cachedir = "$(reltohome $MAIL_CACHE_DIR)/{mail}/mutt/"

set mbox_type = Maildir
set folder = "$(reltohome $MAIL_CACHE_DIR)/{mail}/data"

set spoolfile = +Inbox
set postponed = +Drafts
set record = +Sent
set trash = +Trash

set from = {mail}
set realname = '{mail}'
set sendmail = "msmtp -C $MAIL_CONF_DIR/{mail}/msmtprc -a mail"

set nm_config_file = "$(reltohome $MAIL_CONF_DIR)/{mail}/notmuchrc"
set nm_record = yes
set nm_record_tags = "sent"

mailboxes +Inbox +Drafts +Sent \`find "$(reltohome $MAIL_CACHE_DIR)/{mail}/data" -type d -name cur -not \( -path "*/Inbox/*" -o -path "*/Drafts/*" -o -path "*/Sent/*" -o -path "*/Spam/*" -o -path "*/Trash/*" \) -printf "'%h' " | sort -t/\` +Spam +Trash
EOM

read -r -d '' PASSFETCH << EOM || :
#!/bin/bash

password() { oauth2mail show {mail}; }

password
EOM

#----------------------------------------------------------------------
# Actions
#----------------------------------------------------------------------
generate() {
    local mail="$1"
    local mailconfdir=$(mailconfdir "$mail")
    local imap_host="imap.sample.com"
    local smtp_host="smtp.sample.com"
    populate "$MBSYNCRC"     "$imap_host" "$mail" > "$mailconfdir/mbsyncrc"
    populate "$IMAPNOTIFYRC" "$imap_host" "$mail" > "$mailconfdir/imapnotifyrc.yaml"
    populate "$MSMTPRC"      "$smtp_host" "$mail" > "$mailconfdir/msmtprc"
    populate "$NOTMUCHRC"    ""           "$mail" > "$mailconfdir/notmuchrc"
    populate "$MUTTRC"       ""           "$mail" > "$mailconfdir/muttrc"
    populate "$PASSFETCH"    ""           "$mail" > "$mailconfdir/passfetch"
    find "$mailconfdir" -type d -exec chmod 700 {} \;
    find "$mailconfdir" -type f -exec chmod 600 {} \;
    chmod u+x "$mailconfdir/passfetch"
}

#----------------------------------------------------------------------
# Commands
#----------------------------------------------------------------------
add() {
    local mail="$1"
    local mailconfdir=$(mailconfdir "$mail")
    if [ -d "$mailconfdir" ]; then
        die "add: mailconf dir for email \"$mail\" already exists"
    fi

    mkdir -p "$mailconfdir"
    generate "$mail"
}

sync() {
    local mail="$1"
    local mailconfdir=$(mailconfdir "$mail")
    local mailcachedir=$(mailcachedir "$mail")
    if [ ! -d "$mailconfdir" ]; then
        die "sync: mailconf dir for email \"$mail\" does not exist"
    fi

    [ ! -d "$mailcachedir" ] && mkdir -p "$mailcachedir/data"
    mbsync -Va -c "$mailconfdir/mbsyncrc" |& prefix "mbsync: "
}

watch() {
    local mail="$1"
    local mailconfdir=$(mailconfdir "$mail")
    local mailcachedir=$(mailcachedir "$mail")
    if [ ! -d "$mailconfdir" ]; then
        die "watch: mailconf dir for email \"$mail\" does not exist"
    fi

    [ ! -d "$mailcachedir" ] && mkdir -p "$mailcachedir/data"
    goimapnotify -conf "$mailconfdir/imapnotifyrc.yaml" |& stdbuf -oL cut -d ' ' -f2- | prefix "goimapnotify: "
}

index() {
    local mail="$1"
    local mailconfdir=$(mailconfdir "$mail")
    local mailcachedir=$(mailcachedir "$mail")
    if [ ! -d "$mailconfdir" ]; then
        die "index: mailconf dir for email \"$mail\" does not exist"
    fi

    [ ! -d "$mailcachedir" ] && mkdir -p "$mailcachedir/data"
    notmuch --config "$mailconfdir/notmuchrc" new |& prefix "notmuch: "
}

children() {
    local children=$(ps -o pid= --ppid "$1")
    for pid in $children; do
        children "$pid"
    done
    echo "$children"
}

daemon() {
    local mail="$1"
    local mailconfdir=$(mailconfdir "$mail")
    local mailstatedir=$(mailstatedir "$mail")
    if [ ! -d "$mailconfdir" ]; then
        die "daemon: mailconf dir for email \"$mail\" does not exist"
    fi

    [ ! -d "$mailstatedir" ] && mkdir -p "$mailstatedir"
    local pipe="$mailstatedir/control"
    if [ -p "$pipe" ]; then
        die "daemon: control fifo for email \"$mail\" already exists, is the daemon already running?"
    fi

    mkfifo $pipe
    trap "rm -f $pipe" SIGINT SIGTERM EXIT

    log "Watching inbox for \"$mail\""
    watch "$mail" &
    local watch_pid=$!

    log "Starting timer to send periodic events"
    while true; do
        log "Requesting periodic sync"
        control "$mail" sync
        sleep 300
    done &
    local scheduled_pid=$!

    log "Listening control events for \"$mail\""
    local sync_pid
    while read -r command; do
        local command=($command)
        local cmd="${command[0]}"
        local opts="${command[@]:1}"

        log "Received command: ${cmd} ${opts[@]}"
        case $cmd in
            sync)
                local sync_ppid=$([ ! -z $sync_pid ] && kill -0 $sync_pid &>/dev/null && cat /proc/$sync_pid/stat | cut -d ' ' -f 4)
                if [ -z $sync_pid ] || [[ $sync_ppid != $$ ]]; then
                    {
                        log Syncing "$mail"
                        sync "$mail"
                        log Indexing "$mail"
                        index "$mail"
                        log Done
                    } &
                    sync_pid=$!
                else
                    log "A sync operation is already running, skipping sync"
                fi
                ;;
            exit)
                log "Exiting"
                kill $(children $scheduled_pid) $scheduled_pid
                kill $(children $watch_pid) $watch_pid
                log "Bye"
                break
                ;;
            *)
                log "Unrecognized command: ${command[@]}"
                ;;
        esac
    done < <(tail -f "$pipe")
}

control() {
    local mail="$1"
    local cmd="$2"
    local opts=("${@:3}")
    local mailconfdir=$(mailconfdir "$mail")
    local mailstatedir=$(mailstatedir "$mail")
    if [ ! -d "$mailconfdir" ]; then
        die "daemon: mailconf dir for email \"$mail\" does not exist"
    fi

    local pipe=$mailstatedir/control
    if [ ! -p "$pipe" ]; then
        die "control: control fifo for email \"$mail\" does not exist, is the daemon running?"
    fi
    echo "$cmd" "${opts[@]}" > $pipe
}

remove() {
    local mail="$1"
    local mailconfdir=$(mailconfdir "$mail")
    if [ ! -d "$mailconfdir" ]; then
        die "rm: mailconf dir for email \"$mail\" does not exist"
    fi

    rm -rf $mailconfdir
}

list() {
    find $MAIL_CONF_DIR -mindepth 1 -type d -printf "%f\n"
}

#----------------------------------------------------------------------
# Entrypoint
#----------------------------------------------------------------------
case "$#" in
    0)
        usage ;;
    *)
        for arg in "$@"; do
            case "$arg" in
                -h|--help)
                    help
                    exit 0
                    ;;
                -*)
                    echo "Unexpected option $arg" >&2
                    die "See '$(basename $0) --help' for more information"
                    ;;
            esac
        done
esac

cmd="$1"
shift

case "$cmd" in
    add)
        [ $# -ne 1 ] && die "Usage: $(basename $0) add <email>"
        add "$1"
        ;;
    sync)
        [ $# -ne 1 ] && die "Usage: $(basename $0) sync <email>"
        sync "$1"
        ;;
    watch)
        [ $# -ne 1 ] && die "Usage: $(basename $0) watch <email>"
        watch "$1"
        ;;
    index)
        [ $# -ne 1 ] && die "Usage: $(basename $0) index <email>"
        index "$1"
        ;;
    daemon)
        [ $# -ne 1 ] && die "Usage: $(basename $0) daemon <email>"
        daemon "$1"
        ;;
    control)
        [ $# -lt 2 ] && die "Usage: $(basename $0) control <email> <command> [options...]"
        control "$1" "$2" "${@:3}"
        ;;
    rm)
        [ $# -ne 1 ] && die "Usage: $(basename $0) rm <email>"
        remove "$1"
        ;;
    ls)
        [ $# -ne 0 ] && die "Usage: $(basename $0) ls"
        list
        ;;
    *)
        echo "Unexpected command $cmd" >&2
        die "See '$(basename $0) --help' for more information"
esac
