#!/bin/bash

# Calculate params
export POLYBAR_DPI=$(xrdb -query | grep Xft.dpi | cut -f 2)
export POLYBAR_SCALE=$(bc -l <<< "$POLYBAR_DPI / 96")
export POLYBAR_HEIGHT=$(bc -l <<< "27 * $POLYBAR_SCALE")
export POLYBAR_TRAY_SIZE=$(bc -l <<< "16 * $POLYBAR_SCALE")
export POLYBAR_CPU_HWMON=$(for m in /sys/class/hwmon/*; do [[ -f $m/temp1_input ]] && paste <(cat $m/name) <(echo $m/temp1_input); done | awk '/(coretemp|k10temp)/{print $2}')
export POLYBAR_COLOR_MAIN=$(themectl color `colref main`)
export POLYBAR_COLOR_ALTN=$(themectl color `colref altn`)

# Self reload through signal
rld(){ trap - USR1; pkill -P $$; exec $0; }
trap rld USR1

# Gather the bars
bars=($(grep -Proh "(?<=\[bar/).*(?=\])" $XDG_CONFIG_HOME/polybar/bar.d))

# Launch the bars
for m in $(polybar -m | cut -d":" -f1); do
    for b in ${bars[@]}; do
        echo Launching bar $b
        MONITOR=$m polybar -r $b &
    done
done

# Wait for the bars to finish
wait
