#!/bin/bash

# Reload polybar
pgrep polybar > /dev/null && killall -SIGUSR1 polybar
pkill -f -USR1 polybar-launcher

# Reload conky widgets
pkill -x -USR1 conky

# Reload bspwm colors
bspc config focused_border_color  `xcolor color4`
bspc config presel_feedback_color `xcolor color6`
