#!/bin/bash

# Reset wallpaper
[ -f ~/.fehbg ] && ~/.fehbg &

# Restart window manager
bspc wm -r

# Reload polybar
pkill -f -USR1 polybar-launcher

# Reload conky widgets
pkill -f -USR1 conky-launcher

# Reload bspwm colors
bspc config focused_border_color  `themectl color color4`
bspc config presel_feedback_color `themectl color color6`
