#!/bin/bash
set -e

USAGE="Usage: smbserv [<name:dir>]"

function info { echo "[+] $@"; }
function trace { echo " -  $@"; }

function elevate {
    if (($EUID != 0)); then
        info "Elevating..."
        if [[ -t 1 ]]; then
            sudo "$0" "$@"
        else
            gksu "$0 $@"
        fi
        exit
    fi
}

function setup {
    local smb_conf="
    [global]
      workgroup = WORKGROUP
      map to guest = bad user
      usershare allow guests = yes
    "

    for ds in $SHARES; do
        local share=(${ds//:/ })
        local name=${share[0]}
        local dir=${share[1]}
        trace "Adding share \"$name\" for directory \"$dir\""

        smb_conf+="
        [$name]
          browsable = true
          read only = yes
          guest ok = yes
          path = $dir
        "
    done

    echo "$smb_conf" > /tmp/smb-serv.conf
    smbd -S -F -s /tmp/smb-serv.conf &
    smbd_pid=$!
}

function cleanup {
    info "Cleaning up..."
    if [ ! -z "$smbd_pid" ]; then
        trace "Killing Samba server"
        kill $smbd_pid
    fi
}

case "$#" in
    *)
        case "$1" in
            -h|--help)
                echo "$USAGE"
                exit 0
                ;;
            *)
                SHARES=$@
                ;;
        esac
esac

elevate $@
trap cleanup EXIT

info "Firing up Samba server..."
setup

read -r -d '' _ </dev/tty
