#!/bin/bash
set -e

#----------------------------------------------------------------------
# Help
#----------------------------------------------------------------------
USAGE="Usage: $(basename $0) <command> [args]"
HELP="\
$(basename $0) <command> [args]

Commands:
  status                    Show theme info
  colorscheme [-l] [name]   Show or set colorscheme

Options:
  -h, --help                Print current help message
"

die() { echo >&2 "$*"; exit 1; }
usage() { die "$USAGE"; }
help() { echo "$HELP"; }

#----------------------------------------------------------------------
# Constants
#----------------------------------------------------------------------
THEMECTL_CONF_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/themectl
COLORSCHEME_CACHE_DIR=${XDG_CACHE_HOME:-$HOME/.cache}/colorscheme

#----------------------------------------------------------------------
# Helpers
#----------------------------------------------------------------------
colorscheme_dirs() {
    local search_dirs=("$COLORSCHEME_CACHE_DIR")
    echo "${search_dirs[@]}"
}

colorscheme_list() {
    local colorscheme_dirs="$(colorscheme_dirs)"
    find $colorscheme_dirs -maxdepth 1 -type f -printf "%f\n" | sort | uniq
}

colorscheme_current() {
    local current_file="$THEMECTL_CONF_DIR/colorscheme"
    if [ -f "$current_file" ]; then
        echo $(basename $(readlink -f "$current_file"))
    fi
}

colorscheme_find() {
    local colorscheme="$1"
    local colorscheme_dirs="$(colorscheme_dirs)"
    find $colorscheme_dirs -maxdepth 1 -type f -name "$colorscheme" | head -n 1
}

colorscheme_set() {
    local filepath="$1"
    local current_file="$THEMECTL_CONF_DIR/colorscheme"
    mkdir -p $(dirname "$current_file")
    [ -f "$current_file" ] && rm "$current_file"
    ln -s "$filepath" "$current_file"
}

#----------------------------------------------------------------------
# Commands
#----------------------------------------------------------------------
status() {
    local colorscheme=$(colorscheme_current)
    echo colorscheme: ${colorscheme:-"<unset>"}
}

colorscheme() {
    local arg="$1"
    if [ "$arg" = "-l" ]; then
        colorscheme_list
    elif [ -z "$arg" ]; then
        local current=$(colorscheme_current)
        [ ! -z "$current" ] && echo "$current"
    else
        local filepath=$(colorscheme_find "$arg")
        if [ ! -f "$filepath" ]; then
            die "error: colorscheme \"$arg\" does not exist"
        fi
        echo Applying colorscheme "$arg" from "$filepath"
        colorscheme_set "$filepath"
    fi
}

#----------------------------------------------------------------------
# Entrypoint
#----------------------------------------------------------------------
case "$#" in
    0)
        usage ;;
    *)
        for arg in "$@"; do
            case "$arg" in
                -h|--help)
                    help
                    exit 0
                    ;;
                -*)
                    echo "Unexpected option $arg" >&2
                    die "See '$(basename $0) --help' for more information"
                    ;;
                *)
                    break
                    ;;
            esac
        done
esac

cmd="$1"
shift

case "$cmd" in
    status)
        [ $# -ne 0 ] && die "Usage: $(basename $0) status"
        status
        ;;
    colorscheme)
        [ $# -gt 1 ] && die "Usage: $(basename $0) colorscheme [-l] [name]"
        colorscheme "$1"
        ;;
    *)
        echo "Unexpected command $cmd" >&2
        die "See '$(basename $0) --help' for more information"
esac
