#!/bin/bash
set -e

#----------------------------------------------------------------------
# Help
#----------------------------------------------------------------------
USAGE="Usage: $(basename $0) <command> [args]"
HELP="\
$(basename $0) <command> [args]

Commands:
  status                    Show theme info
  colorscheme [-l] [name]   Show or set colorscheme
  color            <name>   Show color from current colorscheme

Options:
  -h, --help                Print current help message
"

die() { echo >&2 "$*"; exit 1; }
usage() { die "$USAGE"; }
help() { echo "$HELP"; }

#----------------------------------------------------------------------
# Constants
#----------------------------------------------------------------------
THEMECTL_CONF_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/themectl
THEMECTL_CACHE_DIR=${XDG_CACHE_HOME:-$HOME/.cache}/themectl
COLORSCHEME_CACHE_DIR=${XDG_CACHE_HOME:-$HOME/.cache}/colorscheme

#----------------------------------------------------------------------
# Templates
#----------------------------------------------------------------------
read -r -d '' XRESOURCES << EOM || :
!
! {name} theme
!

! special
*.background:   {background}
*.foreground:   {foreground}
*.cursorColor:  {cursor}

! black
*.color0:       {color0}
*.color8:       {color8}

! red
*.color1:       {color1}
*.color9:       {color9}

! green
*.color2:       {color2}
*.color10:      {color10}

! yellow
*.color3:       {color3}
*.color11:      {color11}

! blue
*.color4:       {color4}
*.color12:      {color12}

! magenta
*.color5:       {color5}
*.color13:      {color13}

! cyan
*.color6:       {color6}
*.color14:      {color14}

! white
*.color7:       {color7}
*.color15:      {color15}
EOM

#----------------------------------------------------------------------
# Helpers
#----------------------------------------------------------------------
colorscheme_dirs() {
    local search_dirs=("$COLORSCHEME_CACHE_DIR")
    echo "${search_dirs[@]}"
}

colorscheme_list() {
    local colorscheme_dirs="$(colorscheme_dirs)"
    find $colorscheme_dirs -maxdepth 1 -type f -printf "%f\n" | sort | uniq
}

colorscheme_current() {
    local current_file="$THEMECTL_CONF_DIR/colorscheme"
    if [ -f "$current_file" ]; then
        echo $(basename $(readlink -f "$current_file"))
    fi
}

colorscheme_find() {
    local colorscheme="$1"
    local colorscheme_dirs="$(colorscheme_dirs)"
    find $colorscheme_dirs -maxdepth 1 -type f -name "$colorscheme" | head -n 1
}

colorscheme_set() {
    local filepath="$1"
    local current_file="$THEMECTL_CONF_DIR/colorscheme"
    mkdir -p $(dirname "$current_file")
    [ -f "$current_file" ] && rm "$current_file"
    ln -s "$filepath" "$current_file"
}

colorscheme_mappings() {
    local mappings=(
        "background=.special.background" \
        "foreground=.special.foreground" \
        "cursor=.special.cursor"
    )
    for i in `seq 0 15`; do
        mappings+=("color$i=.colors.color$i")
    done
    echo "${mappings[@]}"
}

colorscheme_xres() {
    local current_file="$THEMECTL_CONF_DIR/colorscheme"
    local mappings="$(colorscheme_mappings)"
    mappings+=("name=.name")

    local args=()
    for m in ${mappings[@]}; do
        local pair=(${m//=/ })
        local name=${pair[0]}
        local value=$(cat "$current_file" | jq -r ${pair[1]})
        args+=("-e s/{$name}/$value/g")
    done
    sed "${args[@]}" <<<"$XRESOURCES"
}

colorscheme_generate_templates() {
    mkdir -p "$THEMECTL_CACHE_DIR"
    colorscheme_xres > "$THEMECTL_CACHE_DIR/colors.Xresources"
}

color_query() {
    local color="$1"
    local current_file="$THEMECTL_CONF_DIR/colorscheme"

    local mappings="$(colorscheme_mappings)"
    for m in ${mappings[@]}; do
        local pair=(${m//=/ })
        local name=${pair[0]}
        if [ "$name" = "$color" ]; then
            local value=$(cat "$current_file" | jq -r ${pair[1]})
            echo "$value"
            break
        fi
    done
}

color_reference() {
    local ref="$1"
    local mappings=( \
        "black=color0" \
        "red=color1" \
        "green=color2" \
        "yellow=color3" \
        "blue=color4" \
        "magenta=color5" \
        "cyan=color6" \
        "white=color7" \
        "bright-black=color8" \
        "bright-red=color9" \
        "bright-green=color10" \
        "bright-yellow=color11" \
        "bright-blue=color12" \
        "bright-magenta=color13" \
        "bright-cyan=color14" \
        "bright-white=color15" \
    )
    for m in ${mappings[@]}; do
        local pair=(${m//=/ })
        local alias=${pair[0]}
        if [ "$alias" = "$ref" ]; then
            local name=${pair[1]}
            color_query "$name"
            break
        fi
    done
}

#----------------------------------------------------------------------
# Commands
#----------------------------------------------------------------------
status() {
    local colorscheme=$(colorscheme_current)
    echo colorscheme: ${colorscheme:-"<unset>"}
}

colorscheme() {
    local arg="$1"
    if [ "$arg" = "-l" ]; then
        colorscheme_list
    elif [ -z "$arg" ]; then
        local current=$(colorscheme_current)
        [ ! -z "$current" ] && echo "$current"
    else
        local filepath=$(colorscheme_find "$arg")
        if [ ! -f "$filepath" ]; then
            die "error: colorscheme \"$arg\" does not exist"
        fi
        echo Applying colorscheme "$arg" from "$filepath"
        colorscheme_set "$filepath"
        colorscheme_generate_templates
    fi
}

color() {
    local color="$1"
    local value=$(color_query "$color")
    if [ -z "$value" ]; then
        value=$(color_reference "$color")
    fi
    [ ! -z "$value" ] && echo "$value"
}

#----------------------------------------------------------------------
# Entrypoint
#----------------------------------------------------------------------
case "$#" in
    0)
        usage ;;
    *)
        for arg in "$@"; do
            case "$arg" in
                -h|--help)
                    help
                    exit 0
                    ;;
                -*)
                    echo "Unexpected option $arg" >&2
                    die "See '$(basename $0) --help' for more information"
                    ;;
                *)
                    break
                    ;;
            esac
        done
esac

cmd="$1"
shift

case "$cmd" in
    status)
        [ $# -ne 0 ] && die "Usage: $(basename $0) status"
        status
        ;;
    colorscheme)
        [ $# -gt 1 ] && die "Usage: $(basename $0) colorscheme [-l] [name]"
        colorscheme "$1"
        ;;
    color)
        [ $# -ne 1 ] && die "Usage: $(basename $0) color <name>"
        color "$1"
        ;;
    *)
        echo "Unexpected command $cmd" >&2
        die "See '$(basename $0) --help' for more information"
esac
