#!/bin/bash
#set -e

#----------------------------------------------------------------------
# Help
#----------------------------------------------------------------------
USAGE="Usage: $(basename $0) <command> [args]"
HELP="\
$(basename $0) <command> [args]

Commands:
  update                    Fetch latest images
  launch    <name> [args]   Launch a new VM instance
  start     <name>          Start an existing VM instance
  stop      <name>          Stop a running VM instance
  delete    <name>          Delete a VM instance
  list                      List VM instances
  shell     <name>          Open a shell inside a VM instance

Options:
  -h, --help                Print current help message
"

die() { echo >&2 "$*"; exit 1; }
usage() { die "$USAGE"; }
help() { echo "$HELP"; }
log() { echo -e "\033[1m> $@\033[0m" >&2; }

#----------------------------------------------------------------------
# Constants
#----------------------------------------------------------------------
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
VM_IMAGE_DIR="${XDG_DATA_HOME}/libvirt/images"
VM_KEY_DIR="${XDG_DATA_HOME}/vm/keys"
VM_NET_IFACE=virbr0
VM_USER=user
DEBIAN_IMAGE_URL="https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2"
FEDORA_IMAGE_URL="https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2"

#----------------------------------------------------------------------
# Helpers
#----------------------------------------------------------------------
require_network() {
    local network=$VM_NET_IFACE
    if [ ! -d /sys/class/net/$network ]; then
        log "Starting VM network \"$network\""
        local active=$(virsh -c qemu:///system net-info default | awk '/Active/{print $2}')
        if [ "$active" != "yes" ]; then
            virsh -c qemu:///system net-start default 1>&2
        fi
    fi
    echo $network
}

fetch_image() {
    local url="$1"
    local fname="$(basename "$url")"

    log "Fetching image \"$fname\""
    curl -s -L -o "$fname" --create-dirs --output-dir "$VM_IMAGE_DIR" "$url"
}

image_url_for_distro() {
    local distro="$1"
    case $distro in
        debian)
            echo "$DEBIAN_IMAGE_URL"
            ;;
        fedora)
            echo "$FEDORA_IMAGE_URL"
            ;;
        *)
            echo "Unexpected distro \"$distro\", falling back to debian" >&2
            echo "$DEBIAN_IMAGE_URL"
            ;;
    esac
}

osinfo_for_distro() {
    local distro="$1"
    case $distro in
        debian)
            echo debian12
            ;;
        fedora)
            echo fedora39
            ;;
        *)
            echo "Unexpected distro \"$distro\", falling back to debian" >&2
            echo debian12
            ;;
    esac
}

require_image() {
    local distro="$1"
    local url="$(image_url_for_distro "$distro")"
    local fname="$(basename "$url")"
    local image=$VM_IMAGE_DIR/$fname
    [ ! -f "$image" ] && fetch_image "$url"
    echo "$image"
}

require_keyfile() {
    local name="$1"
    local keyfile="$VM_KEY_DIR/$name"
    mkdir -p "$VM_KEY_DIR"
    if [ ! -f "$keyfile" ]; then
        ssh-keygen -q -N "" -C "" -f "$keyfile"
    fi
    echo "$keyfile"
}

cloud_init_conf() {
    local name="$1"
    local pubkey="$2"

    cut -c5- <<<"
    #cloud-config
    hostname: $name
    prefer_fqdn_over_hostname: false
    users:
      - default
      - name: $VM_USER
        ssh_authorized_keys:
          - "$pubkey"
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
    "
}

#----------------------------------------------------------------------
# Commands
#----------------------------------------------------------------------
update() {
    for distro in debian fedora; do
        local url="$(image_url_for_distro "$distro")"
        fetch_image "$url"
    done
}

launch() {
    local distro="$1"; shift
    local name="$1"; shift
    if [ -z "$name" ] || [[ "$name" = -* ]]; then
        name="$distro"
        distro="debian"
    fi

    local network=$(require_network)
    local image=$(require_image "$distro")
    local keyfile=$(require_keyfile "$name")

    local volume="$VM_IMAGE_DIR/$name.${image##*.}"
    if [ ! -f "$volume" ]; then
        log "Creating volume \"$(basename "$volume")\" from image \"$(basename "$image")\""
        cp "$image" "$volume"
        virsh pool-refresh --pool default > /dev/null
        virsh vol-resize "$volume" 8G > /dev/null
    fi

    log "Launching VM instance \"$name\" with $distro from image \"$(basename "$image")\" in network \"$network\""
    virt-install \
        --name "$name" \
        --memory 2048 \
        --vcpus 4 \
        --disk=path="$volume" \
        --network bridge=$network \
        --cloud-init user-data=<(cloud_init_conf "$name" "$(cat "$keyfile.pub")"),disable=on \
        --osinfo=$(osinfo_for_distro "$distro") \
        --noautoconsole \
        $@
}

start() {
    local instance="$1"
    require_network >/dev/null

    log "Starting VM instance \"$instance\""
    virsh start "$instance"

    if [ $? -ne 0 ]; then
        log "Forcibly starting VM instance \"$instance\""
        virsh start "$instance" --force-boot
    fi
}

stop() {
    local instance="$1"

    log "Stopping VM instance \"$instance\""
    virsh destroy "$instance"
}

delete() {
    local instance="$1"
    local keyfile=$(require_keyfile "$instance")

    if virsh list --name --state-running | grep -w "$instance" > /dev/null; then
        stop "$instance"
    fi

    log "Deleting VM instance \"$instance\""
    virsh undefine "$instance" --remove-all-storage
    rm -f "$keyfile" "$keyfile.pub"
}

list() {
    virsh list --all --name | sed '/^$/d'
}

console() {
    local instance="$1"
    virsh console "$instance"
}

shell() {
    local instance="$1"
    shift
    ssh -t \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o LogLevel=error \
        -i "$VM_KEY_DIR/$instance" \
        $VM_USER@$instance $@
}

#----------------------------------------------------------------------
# Entrypoint
#----------------------------------------------------------------------
case "$#" in
    0)
        usage ;;
    *)
        for arg in "$@"; do
            case "$arg" in
                -h|--help)
                    help
                    exit 0
                    ;;
                -*)
                    echo "Unexpected option $arg" >&2
                    die "See '$(basename $0) --help' for more information"
                    ;;
                *)
                    break
                    ;;
            esac
        done
esac

cmd="$1"
shift

case "$cmd" in
    update)
        [ $# -ne 0 ] && die "Usage: $(basename $0) $cmd"
        update
        ;;
    launch)
        [ $# -lt 1 ] && die "Usage: $(basename $0) $cmd [distro] <name>"
        launch "$@"
        ;;
    start)
        [ $# -ne 1 ] && die "Usage: $(basename $0) $cmd <instance>"
        start "$1"
        ;;
    stop)
        [ $# -ne 1 ] && die "Usage: $(basename $0) $cmd <instance>"
        stop "$1"
        ;;
    delete)
        [ $# -ne 1 ] && die "Usage: $(basename $0) $cmd <instance>"
        delete "$1"
        ;;
    list)
        [ $# -ne 0 ] && die "Usage: $(basename $0) $cmd"
        list
        ;;
    console)
        [ $# -ne 1 ] && die "Usage: $(basename $0) $cmd <instance>"
        console "$1"
        ;;
    shell)
        [ $# -lt 1 ] && die "Usage: $(basename $0) $cmd <instance>"
        inst="$1"
        shift
        shell "$inst" "$@"
        ;;
    *)
        echo "Unexpected command $cmd" >&2
        die "See '$(basename $0) --help' for more information"
esac
