#!/bin/bash
set -e

#----------------------------------------------------------------------
# Help
#----------------------------------------------------------------------
USAGE="Usage: wallctl [help|list|blur <region>|change <wallpaper>]"
HELP="\
wallctl <command>
Basic commands:
  h,help                        print this help message
  l,list                        list available wallpapers
  b,blur <left|right|both|none> blur currently set wallpaper region
  c,change <wallpaper>          change wallpaper to <wallpaper>
"

die() {
    echo >&2 "$*"
    exit 1
}

#----------------------------------------------------------------------
# Actions
#----------------------------------------------------------------------
WALLPAPERS=~/Wallpapers
CACHE_DIR=~/.cache/wallmon

list() {
    [ ! -d "$WALLPAPERS" ] && die "error: wallpapers directory '$WALLPAPERS' doesn't exist"
    cd "$WALLPAPERS"
    counter=0
    for file in *; do
        echo "$counter) ${file}"
        (( ++counter ))
    done
}

blurred_wallpaper_path() {
    local region=$2
    local curwallext="${1##*.}"
    local curwallfname=$(basename "$1")
    local fnamenoext=${curwallfname%.*}
    local blurwall=$CACHE_DIR/${fnamenoext}_blurred_${region}.$curwallext
    echo $blurwall
}

preprocess_wallpaper() {
    [ ! -d "$CACHE_DIR" ] && mkdir -p $CACHE_DIR
    local wall_w=$(identify -format "%[fx:w]" $1)
    for region in left right both; do
        blurwall=$(blurred_wallpaper_path $1 $region)
        if [ ! -f $blurwall ]; then
            echo Creating \($region\) blurred version of $1
            local region_param=
            case $region in
                left)
                    region_param=50%x100%+0+0
                    ;;
                right)
                    region_param=50%x100%+$((wall_w / 2))+0
                    ;;
                both)
                    region_param=100%x100%+0+0
                    ;;
            esac
            local shrink_perc=10 # Percentage
            convert $1 -region $region_param \
                       -resize $shrink_perc% \
                       -blur 0x8 \
                       -resize $(((100 / shrink_perc) * 100))% \
                       $blurwall
        fi
    done
}

wallpaper_set() {
    feh --bg-scale --no-xinerama $1
}

# Non persistent version (to be used by the blur option)
wallpaper_set_temp() {
    feh --no-fehbg --bg-scale --no-xinerama $1
}

blur() {
    local curwall=$(cat ~/.fehbg | grep feh | cut -d ' ' -f4 | sed "s/'//g")
    case $1 in
        left|right|both)
            local blurwall=$(blurred_wallpaper_path $(basename $curwall) $1)
            if [ ! -f $blurwall ]; then
                echo Could not find $1 blurred version of \"$curwall\" \($blurwall\)
                echo Did you set this wallpaper using "wallctl change"?
                return
            fi
            echo Setting wallpaper to $blurwall
            wallpaper_set_temp $blurwall
            ;;
        none)
            echo Setting wallpaper to $curwall
            wallpaper_set_temp $curwall
            ;;
        *)
            echo Blur command parameter must be either left\|right\|both\|none
            return
    esac
}

wallpaper_change() {
    if ! [[ $1 =~ ^[0-9]+$ ]]; then
        echo Incorrect index!
        return
    fi
    # Pick wallpaper using index
    nwall=$(list | grep -P -o "(?<=$1\)\s).*$")
    # Create blurred version
    preprocess_wallpaper $WALLPAPERS/$nwall
    # Set it active
    echo Changing wallpaper to "$nwall"
    wallpaper_set $WALLPAPERS/$nwall
}

#----------------------------------------------------------------------
# Command line interface
#----------------------------------------------------------------------
usage() {
    die "$USAGE"
}

help() {
    echo "$HELP"
}

case "$#" in
    0)
        usage ;;
    *)
        cmd="$1"
        shift
        case "$cmd" in
            h|help)
                help ;;
            l|list)
                list ;;
            b|blur)
                [ $# -ne 1 ] && usage
                case "$1" in
                    left|right|both|none)
                        blur "$1" ;;
                    *)
                        usage ;;
                esac
                ;;
            c|change)
                [ $# -ne 1 ] && usage
                wallpaper_change "$1" ;;
            *)
                usage ;;
        esac
esac
