#! /bin/sh

bspc config border_width        2
bspc config window_gap         20       # Default=12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf121') $(echo -e '\uf120') $(echo -e '\uf07c') $(echo -e '\uf0ac') $(echo -e '\uf0c3') $(echo -e '\uf001') $(echo -e '\uf141')

sxhkd &
panel &
