#!/bin/bash

bspc config border_width        2
bspc config window_gap         20       # Default=12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config click_to_focus      any
bspc config focused_border_color `xcolor color4`

for m in $(bspc query -M); do
    bspc monitor $m -d $(echo -e '\ue174') $(echo -e '\ue175') $(echo -e '\ue176') $(echo -e '\ue177')
done

if [ ! -z "$BSPWM_PERSIST_WND_STATE" ]; then
    source $(dirname $0)/bspwm_persist
    bspwm_state_track_loop &
    bspc config external_rules_command $(dirname $0)/bspwm_rules_fetcher
fi

sxhkd &
panel &
