#! /bin/sh

bspc config border_width        2
bspc config window_gap         20       # Default=12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d $(echo -e '\ue174') $(echo -e '\ue175') $(echo -e '\ue176') $(echo -e '\ue177')

panel &
