#!/bin/bash

ROOT=$1
[ ! -d "$ROOT" ] && (echo "Usage: $(basename $0) <root>"; exit)

# Make directory structure
echo [+] Making directory structure
mkdir -p $ROOT/boot
mkdir -p $ROOT/sources

# Add info stubs
echo [+] Generating info stubs
echo "Put bcd and boot.sdi files here" > $ROOT/boot/README
echo "Put boot.wim file here"          > $ROOT/sources/README

# Fetch files
echo [+] Fetching needed files
wget -q -P $ROOT http://boot.ipxe.org/ipxe.efi
wget -q -P $ROOT http://boot.ipxe.org/ipxe.lkrn
wget -q -P $ROOT http://boot.ipxe.org/undionly.kpxe
wget -q -P $ROOT https://github.com/ipxe/wimboot/releases/latest/download/wimboot

# Write scripts/configuration
echo [+] Writing configuration files
cat > $ROOT/boot.ipxe <<- EOM
#!ipxe

kernel wimboot
initrd install.bat      install.bat
initrd winpeshl.ini     winpeshl.ini
initrd boot/bcd         BCD
initrd boot/boot.sdi    boot.sdi
initrd sources/boot.wim boot.wim
boot
EOM

cat > $ROOT/install.bat <<- EOM
echo Wait for it...
wpeinit.exe
::wpeutil WaitForNetwork
ipconfig
pause
net use Z: \\\\192.168.0.1\winiso
Z:\setup.exe
EOM

cat > $ROOT/winpeshl.ini <<- EOM
[LaunchApps]
"install.bat"
EOM

echo [+] Done.
