#!/bin/bash

# Reload polybar
pgrep polybar > /dev/null && killall -SIGUSR1 polybar

# Reload conky widgets
killall -SIGUSR1 conky

# Reload bspwm colors
bspc config focused_border_color  `xcolor color4`
bspc config presel_feedback_color `xcolor color6`
