#!/bin/sh

# Setup mappings
source $(dirname $0)/mappings

# Setup inputs
source $(dirname $0)/inputs

# Setup environment
source $(dirname $0)/environment

# Setup interoperability
riverctl spawn $(dirname $0)/interop

# Setup xorg settings for XWayland programs
riverctl spawn $(dirname $0)/xsetup

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set border width
riverctl border-width 2

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl rule-add -app-id "float" float
riverctl rule-add -title "popup title with spaces" float

# Set app-ids and titles of views which should use client side decorations
riverctl rule-add -app-id "gedit" csd

# Wallpaper
riverctl spawn "swaybg -m fill -i $(awk '/feh/{print $4}' ~/.fehbg)"

# Programs
riverctl spawn waybar
riverctl spawn kanshi

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
exec rivertile -view-padding 6 -outer-padding 6
