#!/bin/sh

# Use the "super" key as the primary modifier
mod="Mod4"

# Reload mappings
riverctl map normal $mod Escape spawn $0

# Reload waybar
riverctl map normal $mod+Control Escape spawn "pkill waybar; waybar"

# Launch Terminal
riverctl map normal $mod Return spawn foot

# Open Launcher
riverctl map normal $mod Space spawn bemenu-run

# Open Browser
riverctl map normal $mod I spawn chromium

# Close the focused view
riverctl map normal $mod W close

# Exit river
riverctl map normal $mod+Mod1 Escape exit

# Focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Swap the focused view with the next/previous view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Bump the focused view to the top of the layout stack
riverctl map normal $mod O zoom

# Decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# Snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Move views with mouse
riverctl map-pointer normal $mod BTN_LEFT move-view

# Resize views with mouse
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))

    # Focus tag
    riverctl map normal $mod $i set-focused-tags $tags

    # Tag focused view with tag
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Toggle focus of tag
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Toggle tag of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Focus all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags

# Tag focused view with all tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Toggle float
riverctl map normal $mod S toggle-float

# Toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode.
# This mode has only a single mapping to return to normal mode.
# This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Media key mappings for both normal and locked mode which do not have a modifier
for mode in normal locked; do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 1%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 1%-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

    # Control MPRIS aware media players
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brighness
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done
