[colors.primary]
foreground = "#cccccc"
background = "#1b1d1e"

[colors.cursor]
text   = "#000000"
cursor = "#ffffff"

[colors.selection]
text       = "#eaeaea"
background = "#404040"

[colors.normal]
black   = "#000000"
red     = "#d54e53"
green   = "#b9ca4a"
yellow  = "#e6c547"
blue    = "#7aa6da"
magenta = "#c397d8"
cyan    = "#70c0ba"
white   = "#eaeaea"

[colors.bright]
black   = "#666666"
red     = "#ff3334"
green   = "#9ec400"
yellow  = "#e7c547"
blue    = "#7aa6da"
magenta = "#b77ee0"
cyan    = "#54ced6"
white   = "#ffffff"
